// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VariableConverter
{
    internal sealed partial class Vsix
    {
        public const string Id = "VariableConverter.2e26e412-91b4-4452-84e4-588b98a50835";
        public const string Name = "VariableConverter";
        public const string Description = @"可将中文变量转换从英文和拼音，英文调用的是百度翻译的API，可以自行配置百度翻译的APPId和Secret。百度翻译：https://fanyi-api.baidu.com/product/11，项目地址：https://github.com/liupade40/VariableConverter。";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
