// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VariableConverter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VariableConverterString = "6d1530f7-4267-4d4a-9b9d-ff2c14596044";
        public static Guid VariableConverter = new Guid(VariableConverterString);

        public const string guidVariableConverterPackageCmdSetString = "b7f9edf4-94b5-4d63-9b53-a5f3985007de";
        public static Guid guidVariableConverterPackageCmdSet = new Guid(guidVariableConverterPackageCmdSetString);

        public const string guidImagesString = "19e11dd6-a2e2-4b17-a860-f556c718063a";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "798876d3-e72c-4967-9cef-fe13aa34fb96";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CommandNewId = 0x3110;
        public const int RightClickMenuNewGroup = 0x3100;
        public const int cmdidChineseToPinYinCommand = 0x1021;
        public const int NewRightClickMenuGroup = 0x3200;
        public const int cmdidChineseToEnglishCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006; 
    }
}